modLoader = "javafml"
loaderVersion = "[49,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "yesserusers_discord_rich_presence_mod"
version = "${version}"
displayName = "yesseruser's Discord Rich Presence Mod"
authors = "yesseruser"
description = '''
This mod adds support for Discord Rich Presence which shares a lot of information about the game.
'''
#logoFile = ""

[[dependencies.yesserusers_discord_rich_presence_mod]]
modId = "forge"
mandatory = true
versionRange = "[49,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.yesserusers_discord_rich_presence_mod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.yesserusers_discord_rich_presence_mod]]
modId = "architectury"
mandatory = true
versionRange = "[11.1.17,)"
ordering = "AFTER"
side = "BOTH"
